<?php
/**
 * Created by PhpStorm.
 * User: ???????
 * Date: 24.02.2016
 * Time: 23:00
 */


?>

<script>
    $(function () {
        'use strict';

        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: baseUrl + 'api/addvehicleajax'
        });

        // Enable iframe cross-domain access via redirect option:
        $('#fileupload').fileupload(
            'option',
            'redirect',
            window.location.href.replace(
                /\/[^\/]*$/,
                '/cors/result.html?%s'
            )
        );

        // Load existing files:
        $('#fileupload').addClass('fileupload-processing');
        $.ajax({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: baseUrl + 'api/addvehicleajax',
            dataType: 'json',
            context: $('#fileupload')[0]
        }).always(function () {
            $(this).removeClass('fileupload-processing');
        }).done(function (result) {
            $(this).fileupload('option', 'done')
                .call(this, $.Event('done'), {result: result});
        });
    });
</script>
<div class="container">
	<?
	$form = $this->form;
	$form->prepare();
	echo $this->form()->openTag($form);
	?>
	<div class="row">
		<div class="col-xs-12 col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">add new vehicle</h3>
				</div>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-4 form-group">
						<? echo $this->formRow($form->get('brand')); ?>
					</div>
					<div class="col-md-4 form-group">
						<? echo $this->formRow($form->get('regnum')); ?>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4 form-group">
						<? echo $this->formRow($form->get('submit')); ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<?	echo $this->form()->closeTag($form);?>

	<?=$this->partial('partial-upload.phtml');?>
</div>