<?php
/**
 * Created by PhpStorm.
 * User: ???????
 * Date: 24.02.2016
 * Time: 23:00
 */


?>

<script>
    $(function () {
        'use strict';

        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: baseUrl + 'api/addvehicleajax'
        });

        // Enable iframe cross-domain access via redirect option:
        $('#fileupload').fileupload(
            'option',
            'redirect',
            window.location.href.replace(
                /\/[^\/]*$/,
                '/cors/result.html?%s'
            )
        );

        // Load existing files:
        $('#fileupload').addClass('fileupload-processing');
        $.ajax({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: baseUrl + 'api/addvehicleajax',
            dataType: 'json',
            context: $('#fileupload')[0]
        }).always(function () {
            $(this).removeClass('fileupload-processing');
        }).done(function (result) {
            $(this).fileupload('option', 'done')
                .call(this, $.Event('done'), {result: result});
        });
    });
</script>

<div class="emptySpace20px"></div>
<div class="container">
	<?
	$form = $this->form;
	$form->prepare();

	?>
    <div class="row row-centered">
        <div class="col-xs-6 col-md-12  col-lg-12">
            <div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Добавить новое ТС</h3>
				</div>
                <div class="emptySpace40px"></div>
                <?echo $this->form()->openTag($form);?>
                    <div class="row">
                        <div class="col-md-8 col-lg-8 col-xs-8 col-md-offset-1 col-lg-offset-1 col-xs-offset-1">
                            <div class="col-md-4 form-group" id="int_cnt1">
                                <? echo $this->formRow($form->get('regnumSearch')); ?>
                                <ul id="searchVehicleUl_id"><li>dfsvfvfv</li><li>dfsvfvfv3456</li><li>dfsvfvfv3456</li><li>dfsvfvfv3456</li></ul>
                            </div>
                            <div class="col-md-4 form-group">
                                <? echo $this->formRow($form->get('regnum')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-lg-8 col-xs-8 col-md-offset-1 col-lg-offset-1 col-xs-offset-1">
                            <div class="col-md-4 form-group">
                                <? echo $this->formRow($form->get('submit')); ?>
                            </div>
                        </div>
                    </div>
                <?	echo $this->form()->closeTag($form);?>
                <div class="emptySpace40px"></div>
                <div class="row">
                    <div class="col-md-10 col-lg-10 col-xs-10 col-md-offset-1 col-lg-offset-1 col-xs-offset-1">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Фотографии ТС</h3>
                            </div>
                            <div class="panel-body">


                                <?=$this->partial('partial-upload.phtml');?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="emptySpace20px"></div>
			</div>

		</div>
	</div>


</div>
