<?php
/**
 * Created by PhpStorm.
 * User: Ярослав
 * Date: 06.03.2016
 * Time: 20:25
 */

$images = $this->images;
$form = $this->form;
$form->prepare();

?>

<link rel="stylesheet" href="/roadaccident/public/blueimpgallery/css/blueimp-gallery.min.css">

<script>
    $(function () {
        'use strict';

        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: baseUrl + 'api/addvehicleajax'
        });

        // Enable iframe cross-domain access via redirect option:
        $('#fileupload').fileupload(
            'option',
            'redirect',
            window.location.href.replace(
                /\/[^\/]*$/,
                '/cors/result.html?%s'
            )
        );

        // Load existing files:
        $('#fileupload').addClass('fileupload-processing');
        $.ajax({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: baseUrl + 'api/addvehicleajax',
            dataType: 'json',
            context: $('#fileupload')[0]
        }).always(function () {
            $(this).removeClass('fileupload-processing');
        }).done(function (result) {
            $(this).fileupload('option', 'done')
                .call(this, $.Event('done'), {result: result});
        });
    });
</script>
<div class="emptySpace20px"></div>
<div class="container">
	<div class="row">
		<div class="col-xs-6 col-md-12  col-lg-12">
			<?=$this->form()->openTag($form); ?>
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Автономер <?=$form->get('regnum')->getValue(); ?></h3>
				</div>
                <div class="emptySpace40px"></div>
                <div class="row">
                    <div class="col-md-8 col-lg-8 col-xs-8 col-md-offset-1 col-lg-offset-1 col-xs-offset-1">
                        <div class="col-md-4 form-group">
                            <?$form->get('brand')->setAttribute('disabled','disabled');?>
                            <?=$this->formRow($form->get('brand'));?>
                        </div>
                        <div class="col-md-4 form-group">
                            <?$form->get('regnum')->setAttribute('disabled','disabled');?>
                            <? echo $this->formRow($form->get('regnum')); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-lg-8 col-xs-8 col-md-offset-1 col-lg-offset-1 col-xs-offset-1">
                        <div class="col-md-4 form-group">
                            <? echo $this->formRow($form->get('submit')); ?>
                        </div>
                    </div>
				</div>
                <div class="row">
                    <div class="col-md-8 col-lg-8 col-xs-8 col-md-offset-1 col-lg-offset-1 col-xs-offset-1">
                        <div class="col-md-4 form-group">
                            Создан пользователем <span class="badge"><?=$this->user->getUsername();?></span>
                        </div>
                        <div class="col-md-4 form-group">
                            Дата создания <span class="badge"><?=$this->vehicle->getDatecreated()->format('Y-m-d');?></span>
                        </div>
                    </div>
                </div>
                <div class="emptySpace20px"></div>
                <div class="row">
                    <div class="col-md-8 col-lg-8 col-xs-8 col-md-offset-1 col-lg-offset-1 col-xs-offset-1">
                        <div class="col-md-4 form-group">
                            <img src="/roadaccident/public/images/vehicles/<?=$this->vehicle_id?>/regnum.png">
                        </div>
                    </div>
                </div>
                <?=$this->form()->closeTag($form);?>
                <div class="emptySpace20px"></div>
                <div class="row">
                    <div class="col-md-12 col-lg-12 col-xs-12 col-md-offset-1 col-lg-offset-1 col-xs-offset-1">
                        <div class="col-xs-12 col-md-8">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Фотографии ТС</h3>
                                </div>
                                <div class="panel-body">
                                    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
                                        <div class="slides"></div>
                                        <h3 class="title"></h3>
                                        <a class="prev">‹</a>
                                        <a class="next">›</a>
                                        <a class="close">×</a>
                                        <a class="play-pause"></a>
                                        <ol class="indicator"></ol>
                                    </div>
                                    <div id="links">
                                        <?php foreach($images as $image): ?>
                                            <a href="/roadaccident/<?=$image['path']; ?>" title="<?=$image['name']?>">
                                                <img src="/roadaccident/<?=$image['thumbnail']; ?>" alt="<?=$image['name']?>">
                                            </a>
                                        <?php endforeach; ?>
                                    </div>
                                    <div class="emptySpace40px"></div>
                                    <?=$this->partial('partial-upload.phtml');?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
			</div>
		</div>
	</div>




</div>

<script src="/roadaccident/public/blueimpgallery/js/blueimp-gallery.min.js"></script>
<script>
    document.getElementById('links').onclick = function (event) {
        event = event || window.event;
        var target = event.target || event.srcElement,
            link = target.src ? target.parentNode : target,
            options = {index: link, event: event},
            links = this.getElementsByTagName('a');
        blueimp.Gallery(links, options);
    };
</script>