<? $success = $this->success;?>
<?if($success == 'success'):?>
	<div class="row">
		<div class="col-xs-4 col-md-4 col-lg-4 col-xs-offset-4 col-md-offset-4 col-lg-offset-4">
			<h2>
				Аккаунт активирован
			</h2>
			<div class="row">
				<div class="col-xs-6 col-md-6 col-lg-6">
					<img src="<?=$this->basePath('public/img/post_register.gif')?>" />
				</div>
			</div>
			<div class="emptySpace20px"></div>
			<div class="row">
				<div class="col-xs-6 col-md-6 col-lg-6 ">
					<a href="<?=$this->url('image', array('action' => 'add'))?>" class="descr_btn_simple">Авторизоваться</a>
				</div>
			</div>
			<div class="emptySpace40px"></div>
		</div>
	</div>
<?else:?>
	<div class="emptySpace40px"></div>
	<div class="row">
		<div class="col-xs-4 col-md-4 col-lg-4 col-xs-offset-4 col-md-offset-4 col-lg-offset-4">
			<h1>Ой, произошла какая-то ошибка</h1>
		</div>
	</div>	
	<div class="row">
		<div class="col-xs-6 col-md-6 col-lg-6 ">
			<a href="<?=$this->url('image', array('action' => 'add'))?>" class="descr_btn_simple">Авторизоваться</a>
		</div>
	</div>
	<div class="emptySpace40px"></div>
	<div class="emptySpace40px"></div>
	<div class="emptySpace40px"></div>
<?endif;?>