<?php echo $this->doctype(); ?>

<?
	//$user_session = new Container('user');
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Фотографии ДТП cardam.ru')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('/public/css/style.css'))
                        ->prependStylesheet($this->basePath('/public/css/font-awesome.css'))
                        ->prependStylesheet($this->basePath('/public/css/bootstrap.icon-large.min.css'))
						->prependStylesheet($this->basePath('/public/css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('/public/css/bootstrap.css'))
                        ->prependStylesheet($this->basePath() . '/public/blueimp/css/jquery.fileupload-ui.css')
                        ->prependStylesheet($this->basePath() . '/public/blueimp/css/blueimp-gallery.min.css')
                        ->prependStylesheet($this->basePath() . '/public/blueimp/css/jquery.fileupload.css')
                        ->prependStylesheet($this->basePath('/public/css/roadaccidentStyle.css'));
						
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()

            ->appendFile($this->basePath('/public/js/ajax_scripts.js'), 'text/javascript')
            ->appendFile($this->basePath('/public/js/ui_scripts.js'), 'text/javascript')
            ->prependFile($this->basePath() . '/public/blueimp/js/jquery.fileupload-ui.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/jquery.fileupload-validate.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/jquery.fileupload-image.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/jquery.fileupload-process.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/jquery.fileupload.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/jquery.iframe-transport.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/jquery.blueimp-gallery.min.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/load-image.all.min.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/tmpl.min.js')
            ->prependFile($this->basePath() . '/public/blueimp/js/vendor/jquery.ui.widget.js')
            //->prependFile($this->basePath() . '/blueimp/js/main.js')
            ->prependFile($this->basePath('/public/js/bootstrap.min.js'))
            ->prependFile($this->basePath('/public/js/jquery.min.js'))
        ; ?>

        <script type='text/javascript'>
            var serverUrl = '<?=$this->serverUrl();?>/';
            var baseUrl = '<?=$this->basePath();?>/';
        </script>

    </head>
	<body>
		<div class="container-fluid">
			<div id="header_row" class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0">
                            <div class="row">
								<div class="emptySpace10px">
								</div>
							</div>
							<div class="row">
                                <div class="col-xs-8 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0">
									<div class="row">
										<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xs-offset-1 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
											<a href="/"><!--<img src="<?=$this->basePath('img/logo-2.png')?>" />-->
												<div class="row">
													<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0">
														<span id="iconSpan" style="">CARDAM.RU</span>
													</div>
												</div>
												<div class="row">
													<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0">
														<span id="underIconSpan" style="">База поврежденных автомобилей</span>
													</div>
												</div>
											</a>
										</div>
										<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4  col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0">
											<ul id="usernavul">
												<?if($user_session->id > 0):?>
													<li><a class="usernavul_a yellowBg" href="<?=$this->url('user', array('action' => 'logout'))?>">Выйти</a></li>
													<li><a class="usernavul_a blackBr" href="#"><span class="glyphicon glyphicon-user"></span> <?=$user_session->username?></a></li>
												<?else:?>
													<li><a class="usernavul_a yellowBg" href="<?=$this->url('user', array('action' => 'login'))?>">Войти</a></li>
													<li><a class="usernavul_a blackBr" href="<?=$this->url('user', array('action' => 'register'))?>">Зарегистрироваться</a></li>
												<?endif;?>
												<?if($user_session->isAdmin == 1):?>
													<li class="usernavul_a"><a class="usernavul_a blackBr" href="<?=$this->url('admin', array('action' => 'index'))?>">Админ</a></li>
												<?endif;?>
											</ul>
										</div>
									</div>
                                    <ul id="navul">
                                        <!--<li class="navulli"><a class="nav_a" href="<?=$this->url('index')?>">Главная</a></li>
                                        <li id="navulliRegNum" class="navulli">
											<ul id="autoregnumUl">
												<li><a class="autoregnumUla" href="<?=$this->url('vehicle', array('action' => 'add'))?>">Новый автономер</a></li>
												<li><a class="autoregnumUla" href="<?=$this->url('vehicle', array('action' => 'page', 'id' => 1))?>">Каталог</a></li>
											</ul>
											<a class="nav_a" href="<?=$this->url('vehicle', array('action' => 'add'))?>">Автономера</a>
										</li>-->
										
                                        <li class="navulli">
                                            
                                        </li>
                                    </ul>
                                </div>
                            </div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="row">
						<?=$this->content?>
					</div>
				</div>
			</div>
		</div>
        <div class="container-fluid">
			<div id="footer" class="row">
				<div class="emptySpace10px"></div>
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0">
					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xs-offset-1 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
							<p>&copy; 2015 - <?php echo date('Y') ?> CARDAM.RU </p>
							<p>Обратная связь: info@cardam.ru</p>
						
						</div>
					</div>
				<div class="emptySpace10px"></div>
			</div>
        </div>
		<?php echo $this->inlineScript() ?>
	</body>
</html>
