<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath() . '/blueimp/css/jquery.fileupload-ui.css')
                        ->prependStylesheet($this->basePath() . '/blueimp/css/blueimp-gallery.min.css')
                        ->prependStylesheet($this->basePath() . '/blueimp/css/jquery.fileupload.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
/*
            ->prependFile($this->basePath() . '/blueimp/js/canvas-to-blob.min.js')

            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-audio.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-video.js')


            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))

            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-angular.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-jquery-ui.js')

            ->prependFile($this->basePath() . '/blueimp/js/cors/jquery.postmessage-transport.js')
            ->prependFile($this->basePath() . '/blueimp/js/cors/jquery.xdr-transport.js')*/

            ->appendFile($this->basePath('js/ajax_scripts.js'), 'text/javascript')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-ui.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-validate.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-image.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-process.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.iframe-transport.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.blueimp-gallery.min.js')
            ->prependFile($this->basePath() . '/blueimp/js/load-image.all.min.js')
            ->prependFile($this->basePath() . '/blueimp/js/tmpl.min.js')
            ->prependFile($this->basePath() . '/blueimp/js/vendor/jquery.ui.widget.js')
            //->prependFile($this->basePath() . '/blueimp/js/main.js')
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ; ?>

        <script type='text/javascript'>
            var serverUrl = '<?=$this->serverUrl();?>/';
            var baseUrl = '<?=$this->basePath();?>/';
        </script>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
