<?php echo $this->doctype(); ?>
<?$searchForm = $this->searchForm;?>
<?
	//$user_session = new Container('user');
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath() . '/blueimp/css/jquery.fileupload-ui.css')
                        ->prependStylesheet($this->basePath() . '/blueimp/css/blueimp-gallery.min.css')
                        ->prependStylesheet($this->basePath() . '/blueimp/css/jquery.fileupload.css')
                        ->prependStylesheet($this->basePath('css/roadaccidentStyle.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
/*
            ->prependFile($this->basePath() . '/blueimp/js/canvas-to-blob.min.js')

            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-audio.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-video.js')


            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))

            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-angular.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-jquery-ui.js')

            ->prependFile($this->basePath() . '/blueimp/js/cors/jquery.postmessage-transport.js')
            ->prependFile($this->basePath() . '/blueimp/js/cors/jquery.xdr-transport.js')*/

            ->appendFile($this->basePath('js/ajax_scripts.js'), 'text/javascript')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-ui.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-validate.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-image.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload-process.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.fileupload.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.iframe-transport.js')
            ->prependFile($this->basePath() . '/blueimp/js/jquery.blueimp-gallery.min.js')
            ->prependFile($this->basePath() . '/blueimp/js/load-image.all.min.js')
            ->prependFile($this->basePath() . '/blueimp/js/tmpl.min.js')
            ->prependFile($this->basePath() . '/blueimp/js/vendor/jquery.ui.widget.js')
            //->prependFile($this->basePath() . '/blueimp/js/main.js')
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ; ?>

        <script type='text/javascript'>
            var serverUrl = '<?=$this->serverUrl();?>/';
            var baseUrl = '<?=$this->basePath();?>/';
        </script>

    </head>
	<body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 col-md-8 col-md-offset-3 col-xs-offset-2">
                    <div><a href="<?=$this->basePath()?>"><img src="<?=$this->basePath('img/logo.png')?>" /></a></div>
                    <div class="collapse navbar-collapse">
                        <?php //
                        echo $this->navigation('navigation')
                                  ->menu()
                                  ->setMinDepth(0)
                                  ->setMaxDepth(0)
                                  ->setUlClass('nav navbar-nav');
                        ?>
                        <? $searchForm->setAttributes(array('action' => $this->url('search', array('action' => 'index'))));?>
                                <?=$this->form()->openTag($searchForm);?>
                        <div class="col-lg-4 col-xs-2">
                            <div class="input-group">

                                <?=$this->formRow($searchForm->get('regnum'))?>
                                <span class="input-group-btn">
                                    <?=$this->formRow($searchForm->get('submit'))?>
                                </span>

                            </div>
                        </div>
                        <?=$this->form()->closeTag($searchForm);?>

                        <ul class="nav nav-pills">
                            <?if($user_session->id > 0):?>
                                <li><a href="<?=$this->url('user', array('action' => 'logout'))?>"><?=$user_session->username; ?>(Выйти)</a></li>
                            <?else:?>
                                <li><a href="<?=$this->url('user', array('action' => 'register'))?>">Регистрация</a></li>
                                <li><a href="<?=$this->url('user', array('action' => 'login'))?>">Войти</a></li>
                            <?endif;?>
                        </ul>

                    </div>
                    <?php echo $this->content; ?>
                    <div class="container">
                        <footer>
                            <p>&copy; 2015 - <?php echo date('Y') ?> by Iaroslav Kasianenko. <?php echo $this->translate('All rights reserved.') ?></p>
                        </footer>
                    </div>
                </div>

            </div>
		</div> 

		<?php echo $this->inlineScript() ?>
	</body>
</html>
