<?php
/**
 * Created by PhpStorm.
 * User: Ярослав
 * Date: 24.02.2016
 * Time: 23:00
 */
$form = $this->form;
$form->prepare();
?>



<div class="container">
    <?echo $this->form()->openTag($form);?>

        <div class="row">
            <div class="col-xs-12 col-md-8">
                <h4><a href=<?echo $this->url('admin', array('action' => 'index'));?>>Назад</a></h4>
            </div>
        </div>
        <div class="emptySpace40px"></div>
        <div class="row">
            <div class="panel panel-default centered">
                <div class="panel-heading">
                    <h3 class="panel-title">Регистрация новой марки</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4 form-group">
                            <? echo $this->formRow($form->get('brandname')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 form-group">
                            <? echo $this->formRow($form->get('suppliernames')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 form-group">
                            <? echo $this->formRow($form->get('submit')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <? echo $this->form()->closeTag($form); ?>
        <div class="row">
            <h2>Марки</h2>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Производитель</th>
                    <th>Выделить</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($brands as $brand): ?>
                    <tr>
                        <td><?=$brand['bname'];?></td>
                        <td><?=$brand['sname'];?></td>
                        <td><input  type="checkbox"/></td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>
        <div class="row">
            <button type="button" class="btn btn-default">Сохранить</button>
            <button type="button" class="btn btn-danger">Удалить</button>
        </div>
        <div class="emptySpace20px"></div>
</div>