<div class="emptySpace40px"></div>
<div class="container">
    <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-xs-offset-1  col-sm-offset-1  col-md-offset-1  col-lg-offset-1">
            <h1><a href="<?php echo $this->url('admin', array('action' => 'addbrand')); ?>">Добавить Марки</a></h1>
        </div>
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-xs-offset-1  col-sm-offset-1  col-md-offset-1  col-lg-offset-1">
            <h1><a href="<?php echo $this->url('admin', array('action' => 'editbrand')); ?>">Править Марки</a></h1>
        </div>
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-xs-offset-1  col-sm-offset-1  col-md-offset-1  col-lg-offset-1">
            <div class="emptySpace60px"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-xs-offset-1  col-sm-offset-1  col-md-offset-1  col-lg-offset-1">
            <h1><a href="<?php echo $this->url('admin', array('action' => 'addsupplier')); ?>">Добавить Производителя</a></h1>
        </div>
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-xs-offset-1  col-sm-offset-1  col-md-offset-1  col-lg-offset-1">
            <h1><a href="<?php echo $this->url('admin', array('action' => 'editsupplier')); ?>">Править Производителя</a></h1>
        </div>
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-xs-offset-1  col-sm-offset-1  col-md-offset-1  col-lg-offset-1">
            <div class="emptySpace60px"></div>
        </div>
    </div>
</div>