<?php
/**
 * Created by PhpStorm.
 * User: Ярослав
 * Date: 24.02.2016
 * Time: 23:00
 */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Регистрация нового пользователя</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4 form-group">
                        <? echo $this->formRow($form->get('username')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <? echo $this->formRow($form->get('email')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <? echo $this->formRow($form->get('password')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <? echo $this->formRow($form->get('password_repeat')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <? echo $this->formRow($form->get('firstname')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <? echo $this->formRow($form->get('lastname')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <? echo $this->formRow($form->get('save')); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<? echo $this->form()->closeTag($form); ?>