<?php
/**
 * Created by PhpStorm.
 * User: Ярослав
 * Date: 07.03.2016
 * Time: 13:38
 */
?>

<form id="fileupload" action="<?php echo $this->url('api', array('action' => 'addvehicleajax')); ?>" method="POST" enctype="multipart/form-data">
    <!-- Redirect browsers with JavaScript disabled to the origin page -->
    <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
        <div class="col-lg-7">
            <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Добавить фото</span>
                    <input type="file" name="files[]" multiple>
                </span>
            <input type="hidden" name="vehicle_uid" value="<? echo $this->vehicle_uid; ?>">
            <input type="hidden" name="vehicle_id" value="<? echo $this->vehicle_id; ?>">
            <!-- The global file processing state -->
            <span class="fileupload-process"></span>
        </div>
        <!-- The global progress state -->
        <div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-success" style="width:0%;"></div>
            </div>
            <!-- The extended global progress state -->
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
</form>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<div id="msgBox"></div>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=baseUrl + 'public/' + file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=baseUrl + 'public/' + file.thumbnailUrl%}"/></a>
                {% } %}
            </span>
        </td>
        <td>
            <!--<p class="name">
                {% if (file.url) { %}
                    <a href="{%=baseUrl + file.url%}" title="{%=file.name%}" download="{%=baseUrl + file.name%}" {%=baseUrl + file.thumbnailUrl?'data-gallery':''%}>{%=baseUrl + file.name%}</a>
                {% } else { %}
                    <span>{%=baseUrl + file.name%}</span>
                {% } %}
            </p>-->
            {% if (file.error) { %}
                <!--<div><span class="label label-danger">Error</span> {%=file.error%}</div>-->
            {% } %}
        </td>
        <td>
			<div class="alert alert-success" role="alert">
				<strong>Фото</strong> добавлено и будет доступно после модерации. После проверки вам придет оповещение на email.
			</div>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
          
        </td>
    </tr>
{% } %}
</script>