<div id="index_main_div" class="container-fluid">



	<div class="row" id="main_div">
		<div class="emptySpace40px"></div>
		<div class="container">	
			<div class="row">
				<div class="col-xs-12 col-md-12 col-lg-12 div-bordered-nocolor-big" >
					<div class="row">
						<div class="col-xs-6 col-md-6 col-lg-6">
							<div class="col-xs-12 col-md-12 col-lg-12 div-bordered-nocolor-big-hdr"  style="font-weight:bold;">
								Огромная база ДТП
							</div>
							<div class="col-xs-12 col-md-12 col-lg-12 div-bordered-nocolor-big-text">
								BazaDTP.RU - содержит базу ДТП в России. 
								<div class="row">
									<ul>
										<li>фото тысяч ТС, попавших в ДТП</li>
										<li>ежендевное обновление базы</li>
									</ul>
									<div class="col-xs-8 col-md-8 col-lg-8">
										<a href="<?=$this->url('vehicle', array('action' => 'add'))?>" class="descr_btn">Добавить новое ТС</a>
									</div>
								</div>
								<div class="row">
									<div class="emptySpace20px"></div>
								</div>
							</div>
						</div>
						<div class="col-xs-6 col-md-6 col-lg-6" >
							<div class="col-xs-12 col-md-12 col-lg-12 div-bordered-nocolor-big-hdr"  style="font-weight:bold;">
								Я здесь впервые
							</div>
							<div class="col-xs-12 col-md-12 col-lg-12 div-bordered-nocolor-big-text">
								Добро пожаловать! На нашем сайте Вы можете: 
								<div class="row">
									<ul>
										<li>искать нужное Вам ТС по регистрационному номеру</li>
										<li>Добавлять новые фото ТС</li>
									</ul>
									<div class="col-xs-8 col-md-8 col-lg-8">
										<a href="<?=$this->url('user', array('action' => 'register'))?>" class="descr_btn">Зарегистрироваться</a>
									</div>	
								</div>	
								<div class="row">
									<div class="emptySpace20px"></div>
								</div>
							</div>

						</div>
					</div>	
					<div class="emptySpace20px"></div>
				</div>
			</div>
			<div class="row row-centered">
				
				<div class="col-xs-3 col-md-3 col-lg-3 div-bordered-nocolor">
					<div class="row row-centered">
						<div class="col-xs-8 col-md-8 col-lg-8  col-xs-offset-2 col-md-offset-2 col-lg-offset-2">
							<span style="font-size:1.5em;" class="glyphicon glyphicon-camera"></span>
						</div>
					</div>
					<div class="row row-centered">
						<div class="col-xs-8 col-md-8 col-lg-8  col-xs-offset-2 col-md-offset-2 col-lg-offset-2">
							Фоткай ДТП
						</div>
					</div>
				</div>
				<div class="col-xs-4 col-md-4 col-lg-4 col-xs-offset-1 col-md-offset-1 col-lg-offset-1  div-bordered-nocolor">
					<div class="row row-centered">	
						<div class="col-xs-10 col-md-10 col-lg-10  col-xs-offset-1 col-md-offset-1 col-lg-offset-1">
							<span style="font-size:1.5em;" class="glyphicon glyphicon-search"></span>
						</div>
					</div>
					<div class="row row-centered">
							<div class="col-xs-10 col-md-10 col-lg-10  col-xs-offset-1 col-md-offset-1 col-lg-offset-1">
								Ищи авто по регномеру
							</div>
					</div>
				</div>
				<div class="col-xs-3 col-md-3 col-lg-3 col-xs-offset-1 col-md-offset-1 col-lg-offset-1  div-bordered-nocolor">
					<div class="row row-centered">
						<div class="col-xs-10 col-md-10 col-lg-10  col-xs-offset-1 col-md-offset-1 col-lg-offset-1">
							<span style="font-size:1.5em;" class="glyphicon glyphicon-export"></span>
						</div>
					</div>
					<div class="row row-centered">
						<div class="col-xs-10 col-md-10 col-lg-10  col-xs-offset-1 col-md-offset-1 col-lg-offset-1">
							Загружай фотки
						</div>
					</div>
				</div>
			</div>	
		</div>
	</div>	
</div>